 let obj={
     data:[{
        name:'首页',
        key:'0',
        path:'/admin/home',
    },
    {
        name:'商品管理',
        key:'1',
        path:'/admin/food',
        children:[
            {
               name:'商品列表',
               key:'1-0',
               path:'/admin/food/list',
            },
            {
               name:'商品添加',
               key:'1-1',
               path:'/admin/food/add',
            },
        ]
     },
     {
      name:'广告位管理',
      key:'2',
      path:'/admin/banner'
   },

   {
      name:'购物车管理',
      key:'3',
      path:'/admin/cart',
   },
    {
        name:'数据统计',
        key:'4', 
        path:'/admin/echarts',
        children:[
           {
            name:'饼型统计',
            key:'4-0', 
            path:'/admin/echarts/pie',
           },
           {
            name:'折线统计',
            key:'4-1', 
            path:'/admin/echarts/line',
           }
        ]
     },
     {
      name:'用户管理',
      key:'5',
      path:'/admin/user',
      children:[
         {
            name:'商品列表',
            path:'/admin/user/list',
            key:'5-0'
         },
         {
            name:'商品添加',
            path:'/admin/user/add',
            key:'5-1'
         },
         {
            name:'商品上传file',
            path:'/admin/user/file',
            key:'5-2'
         },
         {
            name:'商品上传base64',
            path:'/admin/user/base64',
            key:'5-3'
         }
      ]
   }
       
    
    ]
 }
 
export default  obj